# -*- coding: utf-8 -*-
"""Locks the committed web parity fixture to the shared CalculationEngine.

The fixture (web/tests/e2e/parity-fixtures.json) is generated by
``python3 web/scripts/export-parity-fixtures.py`` from the 147 matrix
scenarios. The Playwright test compares the Pyodide/bridge output against the
fixture; this test ensures the fixture itself never drifts from the engine.
"""

import json
import os

import pytest

from src.core.engine import CalculationEngine

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "web", "tests", "e2e", "parity-fixtures.json"
)


def test_fixture_exists_and_is_complete():
    assert os.path.exists(FIXTURE_PATH), (
        "Run: python3 web/scripts/export-parity-fixtures.py"
    )
    with open(FIXTURE_PATH, encoding="utf-8") as handle:
        cases = json.load(handle)
    assert len(cases) == 147
    for case in cases:
        assert "id" in case and "form" in case and "expected" in case


def test_fixture_matches_shared_engine():
    with open(FIXTURE_PATH, encoding="utf-8") as handle:
        cases = json.load(handle)
    engine = CalculationEngine()
    for case in cases:
        result = engine.calculate(case["form"], {}, "tr")
        calculated = result["calculated"]
        for key, expected in case["expected"].items():
            actual = calculated.get(key)
            if expected is None or actual is None:
                assert actual == expected, (case["id"], key, actual, expected)
            else:
                assert actual == pytest.approx(expected, rel=1e-9, abs=1e-9), (
                    case["id"],
                    key,
                    actual,
                    expected,
                )
